<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <title>MaxLock | <?= $this->title ?></title>
    <!--Meta-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Lupoae Eduard, Neculache Nicu">
    <meta name="description" content="Password manager for management password and protection.">
    <link rel="stylesheet" href="/css/nav-bar.css">
    <link rel="stylesheet" href="/css/account-styles.css">
    <link rel="stylesheet" href="/css/login-box.css">
    <link rel="stylesheet" href="/css/settings.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
          integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
</head>
<header>
    <nav class="nav-bar">
        <a href="/home"><img class="logo" src="/image/Logo1.png" alt="MaxLock"></a>
        <ul class="nav-elements">
            <li><a href="/home">Home</a></li>
            <li><a href="/account/settings"><i
                            class="fas fa-user-cog"></i><?= isset($this->data['username']) ? $this->data['username'] : "Account" ?>
                </a></li>
            <li><a href="/home/logout"><i class="fas fa-sign-out-alt"></i>Sign Out</a></li>
        </ul>
        <div class="nav-close">
            <div class="line-1"></div>
            <div class="line-2"></div>
            <div class="line-3"></div>
        </div>
    </nav>
</header>

<div class="large-logo">
    <img src="/image/Text.png" alt="logo-image">
</div>

<div class="main">
    <div class="main-content">
        <div class="main-header">
            <h4><?= isset($this->data['message']) ? $this->data['message'] : '' ?></h4>
            <h2 class="main-title">Register Account</h2>
            <hr>
        </div>

        <div class="detailed-password">
            <div class="title"><h4>DETAILED PASSWORD ANALYSIS</h4></div>
            <br>
            <div class="all-member-info-pass">
                <div class="member-info-pass">
                    <div class="title">All accounts</div>
                    <div class="info-pass" id="all-accounts">
                        <p><?= isset($this->data['password_count']) ? $this->data['password_count'] : '-' ?></p></div>
                </div>
                <div class="member-info-pass">
                    <div class="title">Week passwords</div>
                    <div class="info-pass" id="weak-passwords">
                        <p><?= isset($this->data['weak_password']) ? $this->data['weak_password'] : '-' ?></p></div>
                </div>
                <div class="member-info-pass">
                    <div class="title">Expired passwords</div>
                    <div class="info-pass" id="expired-passwords">
                        <p><?= isset($this->data['expired_password']) ? $this->data['expired_password'] : '-' ?></p>
                    </div>
                </div>
                <div class="member-info-pass">
                    <div class="title">Identical passwords</div>
                    <div class="info-pass" id="identical-passwords">
                        <p><?= isset($this->data['identical_password']) ? $this->data['identical_password'] : '-' ?></p>
                    </div>
                </div>
            </div>
            <br>
        </div>
        <hr style="margin:30px">
        <div class="search">
            <input type="text" id="searchTerm" placeholder="What site you looking for?">
            <button type="submit" id="searchButton">
                <i class="fa fa-search"></i>
            </button>
        </div>

        <div class="add-button">
            <div class="add-new-info" onclick="document.getElementById('add-account').style.display='block'">
                <p>ADD NEW ACCOUNT</p>
            </div>
        </div>

        <form autocomplete="off"></form><!-- This disable browser save_password pop-up -->
        <!-- modal add-account -->
        <div id="add-account" class="box">
            <form class="box-content animate" action="/account/newPassword" method="POST">
                <div class="add-account-title">
                    <h2>Add new account</h2>
                    <hr style="margin: 10px 17px 0 17px">
                </div>
                <div class="container-login">
                    <div class="form">
                        <input type="text" name="link" placeholder="" autocomplete="off" required/>
                        <label class="label-login">
                            <span class="content-span">Web site</span>
                        </label>
                    </div>
                    <div class="form">
                        <input type="text" name="username" placeholder="" autocomplete="off" required/>
                        <label class="label-login">
                            <span class="content-span">Username, email, phone</span>
                        </label>
                    </div>
                    <div class="form">
                        <input type="password" name="password" placeholder="" autocomplete="off" required/>
                        <label class="label-login">
                            <span class="content-span">Password</span>
                        </label>
                    </div>
                    <div class="strong-bar">
                        <div id="myProgress">
                            <div id="myBar"></div>
                        </div>
                        <p>Very unsafe: 10%</p>
                    </div>
                    <div class="button-z">
                        <button class="button-sp" id="button-gp" type="button">Auto generate strong</button>
                        <button class="button-sp" id="button-cp" type="submit">Save</button>
                    </div>
                </div>
            </form>
        </div>

        <div class="all-info">

            <?php foreach ($this->data['passwords'] as $password) { ?>
                <form action="/account/editPassword/<?= $password['id'] ?>" method="POST" autocomplete="off">
                    <div class="expand-info" id="expand-info">

                        <h2 class="title-info"><?= $password['title'] ?></h2>
                        <div class="second-info">
                            <div class="input-info-web">
                                <p>Web site:</p> <a class="website-info" target="_blank" rel="noopener noreferrer"
                                                    href="<?= $password['link'] ?>"><?= $password['link'] ?></a>
                            </div>
                            <div class="input-info">
                                <p>Last change: </p>
                                <input class="last-info" type="text" value="<?= $password['last_change'] ?>"
                                       autocomplete="off">
                            </div>
                            <div class="input-info">
                                <p>Username: </p>
                                <input class="username-info" type="text" value="<?= $password['username'] ?>"
                                       autocomplete="off">
                            </div>
                            <div class="input-info">
                                <p>Password:</p>
                                <input class="password-info" type="password" value="<?= $password['password'] ?>"
                                       autocomplete="off"><br><br>
                            </div>
                            <input class="password-checkbox" type="checkbox" onclick="myFunction()">Show Password
                            <div class="button-zone">
                                <button class="button-edit" type="button" style="display: block">Edit</button>
                                <button class="button-save" type="submit" style="display: none">Save</button>
                                <button class="button-remove" type="submit"
                                        formaction="/account/deletePassword/<?= $password['id'] ?>">Remove
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            <?php } ?>

            <div id="export-section">
                <h3>Export methods:</h3>
                <h5>Select a method for export account information.</h5>
                <hr>
                <div id="export-type">
                    <button class="button-json">JSON</button>
                    <button class="button-xml">XML</button>
                    <button class="button-csv">CSV</button>
                </div>
            </div>

        </div>
    </div>
</div>
<script src="/javascript"></script>
<script src="/javascript/navbar.js"></script>
<script src="/javascript/user.js"></script>
<script src="/javascript/modal-box.js"></script>
<?php include VIEW . 'footer.phtml'; ?>