<!DOCTYPE html>
<html lang="en">
<head>
    <title>MaxLock | <?= $this->title ?></title>
    <!--Meta-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Lupoae Eduard, Neculache Nicu">
    <meta name="description" content="Password manager for management password and protection.">
    <link rel="stylesheet" href="/css/login-box.css">
    <link rel="stylesheet" href="/css/nav-bar.css">
    <link rel="stylesheet" href="/css/reset-pass.css">
    <link rel="stylesheet" href="/css/some-global.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
          integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
</head>
<body>
