<!DOCTYPE html>
<html lang="en">
<head>
    <title>MaxLock | ERROR</title>
    <!--Meta-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Lupoae Eduard, Neculache Nicu">
    <meta name="description" content="Password manager for management password and protection.">
    <link rel="stylesheet" href="/css/information.css">
    <link rel="stylesheet" href="/css/nav-bar.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
          integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
</head>
<body>
<div class="info-box">
    <div class="title-box">
        <h1 id="title"><?= $this->data['title'] ?></h1>
    </div>

    <hr style="margin:10px 30px 0 30px;">

    <div class="message-box">
        <p id="message-container">
            <?= $this->data['content'] ?>
        </p>
    </div>
    <div class="back-box">
        <a id="back">BACK TO HOMEPAGE</a>
    </div>
</div>

<script>
    // double click selection text
    document.addEventListener('mousedown', function (event) {
        if (event.detail > 1) {
            event.preventDefault();
        }
    }, false);
</script>
</body>
</html>